# Using corr matrix R -- example 9.14 JW

simialr approach to getting factor model like one used with var covar 

in R matrix, assume  diag are h*2 
and epsilon_i = 1/rii where rii is the digonal element in inv R

In [9]:
R_mat = matrix( c(1, .505, .569, .602, .621, .603, 
                 .505, 1, .422, .467, .482, .450, 
                 .569, .422, 1, .926, .877, .878,
                 .602, .467, .926, 1, .874, .894,
                 .621, .482, .877, .874, 1, .937,
                 .603, .450, .878, .894, .937, 1), byrow=TRUE, nrow=6)

In [10]:
R_mat

[,1]  [,2]  [,3]  [,4]  [,5]  [,6] 
[1,] 1.000 0.505 0.569 0.602 0.621 0.603
[2,] 0.505 1.000 0.422 0.467 0.482 0.450
[3,] 0.569 0.422 1.000 0.926 0.877 0.878
[4,] 0.602 0.467 0.926 1.000 0.874 0.894
[5,] 0.621 0.482 0.877 0.874 1.000 0.937
[6,] 0.603 0.450 0.878 0.894 0.937 1.000

In [16]:
egs  = eigen(R_mat)
V = egs$vectors
Lambdas = egs$values
D = diag(egs$values)

In [17]:
e1 <- V[,1]
e2 <- V[,2]
e3 <- V[,3]
e4 <- V[,4]
e5 <- V[,5]
e6 <- V[,6]

In [19]:
Lambdas

[1] 4.45644850 0.78240991 0.45842506 0.16883257 0.07908774 0.05479622

In [20]:
p = dim(R_mat)[1]
sum(Lambdas) 
all.equal(p, sum(Lambdas))

[1] 6

[1] TRUE

In [21]:
#for m = 3 common factors will account a cumulative proportion  as follows 
m = 3

sum(Lambdas[1:m]) / p

[1] 0.9495472

In [24]:
Fl1 = round(sqrt(Lambdas[1]) * e1, 3)
Fl2 = round(sqrt(Lambdas[2]) * e2, 3)
Fl3 = round(sqrt(Lambdas[3]) * e3, 3)

In [43]:
L_star  = matrix(cbind(Fl1,Fl2,Fl3), byrow=FALSE, ncol=3)
L_star

[,1]   [,2]   [,3]  
[1,] -0.741  0.350  0.573
[2,] -0.604  0.721 -0.340
[3,] -0.929 -0.233 -0.075
[4,] -0.943 -0.174 -0.067
[5,] -0.948 -0.143 -0.045
[6,] -0.945 -0.189 -0.047

In [44]:
# calculate communalities 
# h1 = Fl1^2 + Fl2^2 + ... + Flp^2
h2 = round((Fl1**2) + (Fl2**2)  + (Fl3**2),5)
h2

[1] 0.99991 1.00026 0.92296 0.92401 0.92118 0.93096

In [45]:
Epsilon = 1- h2
round(Epsilon,2)

[1] 0.00 0.00 0.08 0.08 0.08 0.07

In [46]:
Estimated_R_mat = L_star %*% t(L_star) + diag(Epsilon)

In [47]:
Estimated_R_mat

[,1]     [,2]     [,3]     [,4]     [,5]     [,6]    
[1,] 1.000000 0.505094 0.563864 0.599472 0.626633 0.607164
[2,] 0.505094 0.999997 0.418623 0.466898 0.484789 0.450491
[3,] 0.563864 0.418623 0.999995 0.921614 0.917386 0.925467
[4,] 0.599472 0.466898 0.921614 1.000004 0.921861 0.927170
[5,] 0.626633 0.484789 0.917386 0.921861 0.999998 0.925002
[6,] 0.607164 0.450491 0.925467 0.927170 0.925002 0.999995

In [48]:
residual_matrix = R_mat -Estimated_R_mat

In [50]:
round(residual_matrix,3)


[,1]   [,2]   [,3]   [,4]   [,5]   [,6]  
[1,]  0.000  0.000  0.005  0.003 -0.006 -0.004
[2,]  0.000  0.000  0.003  0.000 -0.003  0.000
[3,]  0.005  0.003  0.000  0.004 -0.040 -0.047
[4,]  0.003  0.000  0.004  0.000 -0.048 -0.033
[5,] -0.006 -0.003 -0.040 -0.048  0.000  0.012
[6,] -0.004  0.000 -0.047 -0.033  0.012  0.000

In [51]:
# rotation 
varimax(x = L_star)

$loadings

Loadings:
     [,1]   [,2]   [,3]  
[1,] -0.354  0.244  0.903
[2,] -0.234  0.949  0.211
[3,] -0.921  0.166  0.218
[4,] -0.903  0.214  0.252
[5,] -0.888  0.229  0.284
[6,] -0.908  0.192  0.264

                [,1]  [,2]  [,3]
SS loadings    3.455 1.123 1.120
Proportion Var 0.576 0.187 0.187
Cumulative Var 0.576 0.763 0.950

$rotmat
          [,1]       [,2]       [,3]
[1,] 0.8546400 -0.3383596 -0.3938315
[2,] 0.4823863  0.7980278  0.3611857
[3,] 0.1920779 -0.4986627  0.8452465


In [52]:
promax(x = L_star)

$loadings

Loadings:
     [,1]   [,2]   [,3]  
[1,]                0.987
[2,]         0.999       
[3,] -0.996              
[4,] -0.951              
[5,] -0.917              
[6,] -0.957              

                [,1]  [,2]  [,3]
SS loadings    3.653 1.000 0.977
Proportion Var 0.609 0.167 0.163
Cumulative Var 0.609 0.776 0.938

$rotmat
          [,1]       [,2]       [,3]
[1,] 0.8101622 -0.1380378 -0.1706652
[2,] 0.8952654  0.9216360  0.4394164
[3,] 0.4655857 -0.7377482  1.2325794
